### ISSUE TITLE
Trouble with using Before each method in the actual code

### ISSUE THREAD

**Issue by zhamid123** [Achudan/ExcelToJsonConverterForCypress#1]
I'm having trouble with running the code because I always get the undefined error. I am new to Cypress and I can't figure out what Const can I use to access the json. 

 ` beforeEach(() => {
   cy.request('POST', 'http://localhost:3000/getjson',
    {
      excellocation: "file location",               //excel sheet location
      sheetname: "login"                                                                        //sheet name
    }).then(function (response) {
      this.data = response.body[0]                                                               //reponse in form of array of objects. response.body[N], where N is row in sheet.
 
    })
  });

  it('Use Data From Excel', () => {
     cy.visit('site')
    cy.get('@response')
    cy.get('#email').type(email)
  })

**Comment by Achudan** [comment]
To use data in "it", please refer to point 2 of the readme file.
Before that kindly check the node app 'http://localhost:3000/getjson' is up and running.

**Comment by zhamid123** [comment]
can you provide the async, await example in your  "it" example? I tried adding await but it is not returning a value on the postReq. 

I can see the request body is working. When I console.log postReq.body I can see the values but I cannot seem to add the proper await, async to use the data in the actual test.

**Comment by Achudan** [comment]
​it("Test Case -Data driven Model ", async function () {
  var postReq = await cy.request('POST', 'http://localhost:3000/getjson',
    {
      excellocation: "D:\\Projects\\LearnCypress\\cypress\\fixtures\\sample.xlsx",
      sheetname: "Sheet1"
    }).then(response => {
      return response.body
    })
  const postResponse = postReq.body
  const firstRowData = postResponse[0]
  cy.visit('https://www.google.com')
  cy.get('.text').type(firstRowData.searchData)
  homePage.selectGender().select(firstRowData.gender)
})

**Comment by zhamid123** [comment]
![image](https://user-images.githubusercontent.com/38700090/120508766-9d317000-c38d-11eb-93b5-dbd4bbf15c50.png)

When I run the test it never makes it into executing the actual test. Once the Post is completed, the test stops. The API works but I am unable to use the body in the test.

**Comment by Achudan** [comment]
The status code is returning 200. cy.get('.text') is causing the problem.  Try to print values in console and check.
